'use client';
import ArticleMediaGallery from './article-media';
import {useEffect,useState} from 'react';
import {BookOpen,RefreshCw,FileText,Clock3} from 'lucide-react';
import {pick,type Lang,type Story} from '@/lib/news-data';
import type {ArticleResult,ArticleBlock} from '@/lib/article-extract';
export default function ArticleReader({story,lang,sourceLang}:{story:Story;lang:Lang;sourceLang?:Lang}){
 const t=(...v:string[])=>pick(v,lang);
 const [article,setArticle]=useState<ArticleResult|null>(null),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setArticle(null);const timeout=setTimeout(()=>{controller.abort();setArticle({status:'unavailable',sourceUrl:story.url,blocks:[],reason:'network'});setLoading(false)},45000);
  fetch('/api/article?'+new URLSearchParams({url:story.url,lang:sourceLang||story.sourceLanguage||lang}),{signal:controller.signal}).then(async r=>{const result=await r.json() as ArticleResult;if(!result.status)throw Error();if(!controller.signal.aborted)setArticle(result)}).catch(()=>{if(!controller.signal.aborted)setArticle({status:'unavailable',sourceUrl:story.url,blocks:[],reason:'network'})}).finally(()=>{clearTimeout(timeout);if(!controller.signal.aborted)setLoading(false)});
  return()=>{clearTimeout(timeout);controller.abort()};
 },[story.url,story.sourceLanguage,lang,sourceLang,attempt]);
 if(loading)return <section className="reader-loading" role="status" aria-live="polite"><div><BookOpen size={21}/><span>{t('نحمّل القصة من المصدر…','Loading the story from its source…','Загружаем статью из источника…','Artikel wird von der Quelle geladen…')}</span></div><span/><span/><span/><span/></section>;
 const media=<ArticleMediaGallery key={story.url} media={article?.media} image={story.image} lang={lang} source={article?.sourceUrl||story.url}/>;
 if(!article||article.status==='unavailable')return <>{media}<section className="reader-unavailable" role="status"><FileText size={24}/><div><h3>{t('تعذّر تحميل نص المقال هنا','Article text is unavailable here','Текст статьи пока недоступен','Artikeltext hier nicht verfügbar')}</h3><p>{article?.reason==='language-mismatch'?t('لغة هذا المصدر لا تطابق هذه النسخة. انتقل إلى قسم لغة المقال لقراءته.','This source is in another language. Open its language edition to read it.','Язык источника не совпадает с этим разделом. Откройте раздел на языке статьи.','Die Sprache dieser Quelle gehört zu einer anderen Ausgabe. Öffne die Ausgabe in der Artikelsprache.'):article?.reason==='restricted'?t('هذا المقال مقيّد لدى الناشر. لم نتجاوز الاشتراك أو تسجيل الدخول.','This article is restricted by its publisher. Subscription and sign-in requirements are respected.','Издатель ограничил доступ. Подписка и вход не обходятся.','Der Verlag beschränkt den Zugriff. Abo- und Anmeldepflichten werden respektiert.'):article?.reason==='unresolved'?t('لم نتمكّن من الوصول إلى رابط الناشر المباشر من رابط Google News. المعروض أعلاه ملخص فقط.','The Google News link could not be resolved to the publisher’s article. The text above is only a summary.','Не удалось получить прямую ссылку из Google News. Выше показан только краткий обзор.','Der Google-News-Link konnte nicht zum Originalartikel aufgelöst werden. Oben steht nur eine Zusammenfassung.'):t('المصدر لم يوفّر نصاً قابلاً للاستخراج أو منع الاتصال. المعروض أعلاه ملخص فقط، وليس القصة الكاملة.','The publisher did not provide readable article text or blocked the connection. The text above is only a summary, not the full story.','Источник не предоставил читаемый текст или заблокировал соединение. Выше — только краткий обзор, не вся статья.','Die Quelle hat keinen lesbaren Artikeltext geliefert oder den Zugriff blockiert. Oben steht nur eine Zusammenfassung, nicht der ganze Artikel.')}</p><button onClick={()=>setAttempt(a=>a+1)}><RefreshCw size={14}/>{t('حاول مجدداً','Try again','Повторить','Erneut versuchen')}</button><a className="outline-button" href={article?.sourceUrl||story.url} target="_blank" rel="noopener noreferrer">{t('فتح المصدر الأصلي','Open original source','Открыть источник','Originalquelle öffnen')}</a></div></section></>;
 const content=(block:ArticleBlock)=>block.links?block.links.map((part,i)=>part.url?<a key={i} href={part.url} target="_blank" rel="noopener noreferrer">{part.text}</a>:part.text):block.text;
 const nativeNames:Record<string,string>={ar:'العربية',en:'English',de:'Deutsch',ru:'Русский'};
 return <section className="full-article">{media}<div className="reading-meta"><span><BookOpen size={17}/>{article.origin==='feed'?t('نص التغذية من الناشر','Publisher feed text','Текст из ленты издателя','Text aus dem Verlagsfeed'):t('نص المقال','Article text','Текст статьи','Artikeltext')}</span><span><Clock3 size={14}/>{article.minutes} {t('دقائق قراءة','min read','мин чтения','Min. Lesezeit')}</span></div><div className="original-language">{t('بلغة المصدر الأصلية','In the original source language','На языке первоисточника','In der Originalsprache')} · {nativeNames[article.language||'']||article.language||'—'}{article.byline&&<span> · {article.byline}</span>}</div>{article.status==='partial'&&<p className="reader-partial">{t('هذا هو النص الذي يتيحه الناشر في التغذية، وقد يكون مختصراً. تعذّر استخراج الصفحة الكاملة.','This is the text supplied in the publisher’s feed and may be abbreviated. The complete page could not be extracted.','Это текст из ленты издателя; он может быть сокращён. Полную страницу извлечь не удалось.','Dieser Text stammt aus dem Verlagsfeed und kann gekürzt sein. Die vollständige Seite konnte nicht ausgelesen werden.')}</p>}<article className="article-prose" lang={article.language} dir={article.direction||'auto'}>{article.blocks.map((block,index)=>block.type==='heading'?<h3 key={index}>{content(block)}</h3>:block.type==='quote'?<blockquote key={index}>{content(block)}</blockquote>:block.type==='list'?<p className="prose-list" key={index}>{content(block)}</p>:<p key={index}>{content(block)}</p>)}</article><div className="article-end"><span/>{t('نهاية النص المستخرج','End of extracted text','Конец извлечённого текста','Ende des ausgelesenen Textes')}<span/></div></section>
}
