 'use client';
import {useEffect,useState} from 'react';
import {Languages,ChevronDown,Bookmark,RefreshCw} from 'lucide-react';
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from '@/components/ui/collapsible';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {curated,pick,type Lang,type Story} from '@/lib/news-data';
import ArticleReader from './article-reader';
type Translation={title:string;summary:string};
type Saved={key:string;story:Story;from:Lang;to:Lang;translation?:Translation};
const names:Record<Lang,string>={ar:'العربية',en:'English',ru:'Русский',de:'Deutsch'};
const storageKey='nabd-learning-saved-v1';
export default function LearningSection({lang,refreshToken,savedOnly,onCount}:{lang:Lang;refreshToken:string;savedOnly:boolean;onCount:(n:number)=>void}){
 const t=(...v:string[])=>pick(v,lang);
 const [open,setOpen]=useState(false),[from,setFrom]=useState<Lang>('en'),[to,setTo]=useState<Lang>(lang==='en'?'ar':lang),[stories,setStories]=useState<Story[]>([]),[selected,setSelected]=useState<Story|null>(null),[translations,setTranslations]=useState<Record<string,Translation>>({}),[saved,setSaved]=useState<Saved[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[limit,setLimit]=useState(6),[reader,setReader]=useState(false);
 const key=(s:Story,f=from,target=to)=>f+':'+target+':'+s.url;
 useEffect(()=>{try{const items=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(items))setSaved(items);setOpen(localStorage.getItem('nabd-learning-open')==='true')}catch{}setReady(true)},[]);
 useEffect(()=>{onCount(saved.length)},[saved,onCount]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('nabd-learning-open',String(open))}catch{}},[open,ready]);
 useEffect(()=>{if(!(open||savedOnly)||savedOnly)return;const abort=new AbortController();setLoading(true);setError('');fetch('/api/news?'+new URLSearchParams({lang:from,refresh:'1'}),{cache:'no-store',signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{articles:Story[]}>}).then(d=>{setStories([...d.articles,...curated(from).filter(s=>!d.articles.some((a:Story)=>a.url===s.url))]);setLimit(6)}).catch(()=>{if(!abort.signal.aborted)setError(t('تعذّر تحديث الأخبار. حاول مجدداً.','Could not refresh stories. Try again.','Не удалось обновить новости. Повторите.','Nachrichten konnten nicht aktualisiert werden.'))}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[open,savedOnly,from,refreshToken]);
 const entry=selected?saved.find(s=>s.key===key(selected)):undefined;
 const translation=selected?translations[key(selected)]||entry?.translation:undefined;
 async function translate(){if(!selected||busy)return;const chosen=selected,chosenKey=key(selected);setBusy(true);setError('');try{const r=await fetch('/api/translation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:chosen.url,from,to})});if(!r.ok)throw Error();const result=await r.json() as Translation;setTranslations(p=>({...p,[chosenKey]:result}));const existing=saved.find(s=>s.key===chosenKey);if(existing)persist(saved.map(s=>s.key===chosenKey?{...s,translation:result}:s))}catch{setError(t('الترجمة غير متاحة الآن أو وصلت الخدمة إلى حدها اليومي. النص الأصلي ما زال متاحاً.','Translation is unavailable or its daily allowance was reached. The original remains available.','Перевод недоступен или исчерпан дневной лимит. Оригинал доступен.','Übersetzung nicht verfügbar oder Tageslimit erreicht. Das Original bleibt verfügbar.'))}finally{setBusy(false)}}
 function persist(items:Saved[]){try{localStorage.setItem(storageKey,JSON.stringify(items));setSaved(items)}catch{setError(t('تعذّر الحفظ: مساحة المتصفح غير متاحة.','Could not save: browser storage is unavailable.','Не удалось сохранить: хранилище браузера недоступно.','Speichern fehlgeschlagen: Browserspeicher nicht verfügbar.'))}}
 function save(){if(!selected)return;persist(entry?saved.filter(s=>s.key!==entry.key):[{key:key(selected),story:selected,from,to,translation},...saved])}
 function choose(s:Story){setSelected(s);setError('')}
 function chooseSaved(s:Saved){setFrom(s.from);setTo(s.to);choose(s.story)}
 return <Collapsible className="learning-section" open={savedOnly||open} onOpenChange={setOpen}><CollapsibleTrigger className="learning-trigger" disabled={savedOnly}><span><Languages size={24}/><span><strong>{savedOnly?t('المحفوظات لتعلّم اللغات','Saved language-learning stories','Сохранённое для изучения языков','Gespeicherte Lernartikel'):t('تعلّم اللغات عبر الأخبار','Learn languages through news','Изучайте языки по новостям','Sprachen lernen mit Nachrichten')}</strong><small>{t('الأصل والترجمة جنباً إلى جنب','Original and translation, side by side','Оригинал и перевод рядом','Original und Übersetzung nebeneinander')}</small></span></span><span>{savedOnly?saved.length:open?t('إخفاء','Hide','Скрыть','Ausblenden'):t('فتح','Open','Открыть','Öffnen')}<ChevronDown size={18}/></span></CollapsibleTrigger><CollapsibleContent className="learning-content">
 <p className="learning-note">{t('ترجمة العنوان والملخص للتعلّم، وليست ترجمة المقال الكامل. الحفظ يبقي البطاقة والترجمة في هذا المتصفح بعد التحديث؛ مسح بيانات المتصفح يزيل المحفوظات.','Headline and summary translations for learning, not full-article translations. Saving retains the card and translation in this browser across refreshes; clearing browser data removes them.','Перевод заголовка и краткого обзора для обучения, не всей статьи. Сохранённые карточки и переводы остаются в этом браузере после обновления; очистка данных удаляет их.','Übersetzungen von Überschrift und Kurztext zum Lernen, keine vollständigen Artikelübersetzungen. Gespeicherte Karten und Übersetzungen bleiben in diesem Browser nach dem Aktualisieren erhalten; beim Löschen der Browserdaten gehen sie verloren.')}</p>
 {!savedOnly&&<div className="learning-controls">{([['from',from],['to',to]] as const).map(([kind,value])=><label key={kind}>{kind==='from'?t('لغة المصدر','Source language','Язык источника','Quellsprache'):t('لغة الترجمة','Translation language','Язык перевода','Zielsprache')}<Select value={value} disabled={busy} onValueChange={v=>{if(kind==='from'){setFrom(v as Lang);if(v===to)setTo(v==='en'?'ar':'en');setSelected(null)}else setTo(v as Lang);setError('')}}><SelectTrigger aria-label={kind==='from'?'Learning source language':'Learning translation language'}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(names).filter(([l])=>kind==='from'||l!==from).map(([l,n])=><SelectItem key={l} value={l}>{n}</SelectItem>)}</SelectContent></Select></label>)}</div>}
 {loading&&<p role="status"><RefreshCw size={15} className="spin"/> {t('نبحث عن أحدث الأخبار…','Checking for latest stories…','Проверяем свежие новости…','Aktuelle Nachrichten werden gesucht…')}</p>}
 <div className="learning-list">{savedOnly?saved.map(s=><button key={s.key} onClick={()=>chooseSaved(s)}><small>{names[s.from]} → {names[s.to]} · {s.story.source}</small><strong dir="auto">{s.translation?.title||s.story.title}</strong></button>):stories.slice(0,limit).map(s=><button key={s.id} aria-pressed={selected?.id===s.id} onClick={()=>choose(s)}><small>{s.source} · {s.date?new Date(s.date).toLocaleDateString(lang):t('مرجع','Reference','Справочник','Referenz')}</small><strong lang={from} dir={from==='ar'?'rtl':'ltr'}>{s.title}</strong></button>)}</div>
 {!savedOnly&&stories.length>limit&&<button className="outline-button" onClick={()=>setLimit(n=>n+6)}>{t('المزيد من الأخبار','More stories','Ещё новости','Weitere Nachrichten')}</button>}
 {savedOnly&&!saved.length&&<p>{t('لم تحفظ أخباراً للتعلّم بعد.','No learning stories saved yet.','Пока нет сохранённых учебных статей.','Noch keine Lernartikel gespeichert.')}</p>}
 {selected&&<><div className="learning-comparison"><article lang={from} dir={from==='ar'?'rtl':'ltr'}><span className="eyebrow">{names[from]} · {t('الأصل','Original','Оригинал','Original')}</span><h3>{selected.title}</h3><p>{selected.summary}</p></article><article lang={to} dir={to==='ar'?'rtl':'ltr'}><span className="eyebrow">{names[to]} · {t('الترجمة','Translation','Перевод','Übersetzung')}</span>{translation?<><h3>{translation.title}</h3><p>{translation.summary}</p></>:<button className="primary-button" onClick={translate} disabled={busy}>{busy?t('جارٍ الترجمة…','Translating…','Переводим…','Wird übersetzt…'):t('ترجم العنوان والملخص','Translate headline & summary','Перевести заголовок и обзор','Überschrift und Kurztext übersetzen')}</button>}</article></div><p className="learning-note">{t('ترجمة آلية عبر MyMemory للنص العام عند الطلب، وقد تخطئ. المراجع المختارة لها ملخصات مترجمة معدّة مسبقاً.','Public text is machine-translated by MyMemory on request and may contain errors. Selected reference stories use prepared translated summaries.','По запросу публичный текст переводится через MyMemory; возможны ошибки. Для избранных справочных статей есть подготовленные переводы.','Öffentliche Texte werden auf Wunsch mit MyMemory maschinell übersetzt; Fehler sind möglich. Ausgewählte Referenzartikel haben vorbereitete Übersetzungen.')}</p><div className="learning-actions"><button className="primary-button" onClick={save} disabled={!ready} aria-pressed={!!entry}><Bookmark size={17}/>{entry?t('محفوظ · إزالة','Saved · remove','Сохранено · удалить','Gespeichert · entfernen'):t('حفظ للتعلّم','Save for learning','Сохранить для обучения','Zum Lernen speichern')}</button><button className="outline-button" onClick={()=>setReader(true)}>{t('قراءة المقال الأصلي','Read original article','Читать оригинал','Originalartikel lesen')}</button><a className="outline-button" href={selected.url} target="_blank" rel="noreferrer">{t('مرجع المصدر','Source reference','Источник','Quellenlink')}</a></div></>}
 {error&&<p role="alert" className="learning-error">{error}</p>}
 <Dialog open={reader} onOpenChange={setReader}><DialogContent className="article-dialog" dir={lang==='ar'?'rtl':'ltr'}><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{t('المقال بلغة المصدر','Article in its source language','Статья на языке источника','Artikel in der Originalsprache')} · {names[from]}</DialogDescription></DialogHeader>{selected&&<ArticleReader key={selected.url} story={selected} lang={lang} sourceLang={from}/>}</DialogContent></Dialog>
 </CollapsibleContent></Collapsible>
}
