 'use client';
import {useEffect,useMemo,useState} from 'react';
import {Languages,ChevronDown,Bookmark,RefreshCw,BookOpen,ArrowUpRight,Columns2} from 'lucide-react';
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from '@/components/ui/collapsible';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {curated,pick,type Lang,type Story} from '@/lib/news-data';
import {learningLanguages,preparedVersions,mergeLearningSaves,type LearningSave,type Versions} from '@/lib/learning-data';
import ArticleReader from './article-reader';
const names:Record<Lang,string>={ar:'العربية',en:'English',ru:'Русский',de:'Deutsch'};
const storageKey='nabd-learning-saved-v1';
export default function LearningSection({lang,refreshToken,savedOnly,onCount}:{lang:Lang;refreshToken:string;savedOnly:boolean;onCount:(n:number)=>void}){
 const t=(...v:string[])=>pick(v,lang);
 const [open,setOpen]=useState(true),[displayLang,setDisplayLang]=useState<Lang>(lang),[stories,setStories]=useState<Story[]>(curated('en')),[selected,setSelected]=useState<Story|null>(curated('en')[0]),[cache,setCache]=useState<Record<string,Versions>>({}),[saved,setSaved]=useState<LearningSave[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[limit,setLimit]=useState(6),[reader,setReader]=useState(false),[compare,setCompare]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{try{setSaved(mergeLearningSaves(JSON.parse(localStorage.getItem(storageKey)||'[]')));const old=localStorage.getItem('nabd-learning-open');setOpen(old===null||old==='true');setCache(JSON.parse(localStorage.getItem('nabd-learning-translations-v2')||'{}'))}catch{}setReady(true)},[]);
 useEffect(()=>{onCount(saved.length)},[saved,onCount]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('nabd-learning-open',String(open))}catch{}},[open,ready]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('nabd-learning-translations-v2',JSON.stringify(Object.fromEntries(Object.entries(cache).slice(-40))))}catch{}},[cache,ready]);
 useEffect(()=>{if(!open||savedOnly)return;const abort=new AbortController();setLoading(true);fetch('/api/news?lang=en&refresh=1',{cache:'no-store',signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{articles:Story[]}>}).then(d=>{if(abort.signal.aborted)return;setStories([...curated('en'),...d.articles.filter(s=>!curated('en').some(c=>c.url===s.url))]);setLimit(6)}).catch(()=>{if(!abort.signal.aborted)setError(t('تعذّر تحديث القصص، والمختارات ما زالت متاحة.','Could not refresh; selected reference stories are still available.','Не удалось обновить ленту; избранные статьи доступны.','Aktualisierung fehlgeschlagen; ausgewählte Referenzartikel bleiben verfügbar.'))}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[open,savedOnly,refreshToken]);
 const selectedSave=selected?saved.find(s=>s.story.url===selected.url):undefined;
 const versions=selected?{...preparedVersions(selected),...selectedSave?.versions,...cache[selected.url]}:{};
 useEffect(()=>{if(!ready||!selected||(!open&&!savedOnly))return;const story=selected;const from=story.sourceLanguage||'en';const known={...preparedVersions(story),...saved.find(s=>s.story.url===story.url)?.versions,...cache[story.url]};const missing=learningLanguages.filter(l=>!known[l]);if(!missing.length){setBusy(false);return}const abort=new AbortController();setBusy(true);setError('');(async()=>{for(const to of missing){try{const r=await fetch('/api/translation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:story.url,from,to}),signal:abort.signal});if(!r.ok)throw Error();const result=await r.json() as {title:string;summary:string};if(abort.signal.aborted)return;known[to]=result;setCache(p=>({...p,[story.url]:{...p[story.url],...known}}))}catch{if(!abort.signal.aborted)setError(t('توقفت خدمة الترجمة مؤقتاً أو وصل حدها اليومي. اللغات المتاحة محفوظة.','Translation is temporarily unavailable or its daily allowance was reached. Available versions are retained.','Перевод временно недоступен или достигнут дневной лимит. Готовые версии сохранены.','Übersetzung vorübergehend nicht verfügbar oder Tageslimit erreicht. Vorhandene Versionen bleiben erhalten.'));break}}if(!abort.signal.aborted)setBusy(false)})();return()=>abort.abort()},[ready,selected?.url,open,savedOnly,attempt]);
 useEffect(()=>{if(!ready)return;const upgraded=saved.map(s=>({...s,versions:{...s.versions,...cache[s.story.url]}}));try{localStorage.setItem(storageKey,JSON.stringify(upgraded))}catch{setError(t('تعذّر حفظ البيانات في المتصفح.','Browser storage could not save the data.','Не удалось сохранить данные в браузере.','Daten konnten nicht im Browser gespeichert werden.'))}},[saved,cache,ready]);
 const items=savedOnly?saved.map(s=>s.story):stories;
 const active=savedOnly?(selectedSave?selected:null):selected;
 function save(){if(!selected)return;const next=selectedSave?saved.filter(s=>s.story.url!==selected.url):[{key:selected.url,story:selected,versions},...saved];try{localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next)}catch{setError(t('مساحة الحفظ غير متاحة.','Storage is unavailable.','Хранилище недоступно.','Speicher nicht verfügbar.'))}}
 const list=useMemo(()=>items.slice(0,savedOnly?items.length:limit),[items,savedOnly,limit]);
 return <Collapsible className="learning-section learning-studio" open={savedOnly||open} onOpenChange={setOpen}><CollapsibleTrigger className="learning-trigger" disabled={savedOnly}><span><span className="learning-emblem"><Languages size={28}/></span><span><small>{t('مساحة اللغات','THE LANGUAGE STUDIO','ЯЗЫКОВАЯ СТУДИЯ','DAS SPRACHSTUDIO')}</small><strong>{savedOnly?t('قصصك المحفوظة، بأربع لغات','Your saved stories, in four languages','Сохранённые истории на четырёх языках','Deine gespeicherten Geschichten in vier Sprachen'):t('قصة واحدة. أربع لغات.','One story. Four languages.','Одна история. Четыре языка.','Eine Geschichte. Vier Sprachen.')}</strong></span></span><span>{savedOnly?saved.length:open?t('إخفاء','Hide','Скрыть','Ausblenden'):t('فتح','Open','Открыть','Öffnen')}<ChevronDown size={18}/></span></CollapsibleTrigger><CollapsibleContent className="learning-content">
 <div className="learning-toolbar"><Tabs value={displayLang} onValueChange={v=>setDisplayLang(v as Lang)}><TabsList aria-label="Learning language">{learningLanguages.map(l=><TabsTrigger key={l} value={l}>{names[l]}</TabsTrigger>)}</TabsList></Tabs><button className="outline-button" aria-pressed={compare} onClick={()=>setCompare(!compare)}><Columns2 size={16}/>{t('مقارنة الأربع','Compare all four','Сравнить четыре','Alle vier vergleichen')}</button></div>
 <p className="learning-note">{t('اختر القصة نفسها واقرأ عنوانها وملخصها بأربع لغات. تغيير اللغة لا يغيّر القصص. نص المقال الكامل متاح بلغته الأصلية.','Read the same headline and summary in four languages. Switching language keeps the same stories. Full article text is available in its original language.','Читайте один и тот же заголовок и обзор на четырёх языках. Смена языка не меняет истории. Полная статья доступна на языке оригинала.','Lies dieselbe Überschrift und Zusammenfassung in vier Sprachen. Ein Sprachwechsel ändert die Geschichten nicht. Der vollständige Artikel bleibt in seiner Originalsprache.')}</p>
 <div className="learning-workspace"><div className="learning-story-rail">{loading&&<p className="learning-loading" role="status"><RefreshCw className="spin" size={14}/>{t('نحدّث القصص…','Updating stories…','Обновляем…','Wird aktualisiert…')}</p>}{list.map((s,i)=>{const v={...preparedVersions(s),...saved.find(x=>x.story.url===s.url)?.versions,...cache[s.url]}[displayLang];return <button className="lesson-story" key={s.url} aria-pressed={active?.url===s.url} onClick={()=>{setSelected(s);setError('')}}><span className="lesson-number">{String(i+1).padStart(2,'0')}</span><span><small>{s.source} · {s.date?new Date(s.date).toLocaleDateString(lang):t('مرجع','Reference','Справочник','Referenz')}</small><strong lang={v?displayLang:s.sourceLanguage||'en'} dir={v&&displayLang==='ar'?'rtl':'ltr'}>{v?.title||s.title}</strong>{!v&&<small>{t('اختر القصة لتحميل اللغات','Select to load all languages','Выберите для перевода','Auswählen, um Übersetzungen zu laden')}</small>}</span></button>})}{!savedOnly&&items.length>limit&&<button className="outline-button" onClick={()=>setLimit(n=>n+6)}>{t('قصص أكثر','More stories','Ещё истории','Weitere Geschichten')}</button>}</div>
 <div className="lesson-reader">{active?<><div className="lesson-source"><span>{active.source}</span><span>{active.date?new Date(active.date).toLocaleDateString(lang):t('مرجع دائم','Reference','Справочник','Referenz')}</span></div><div className={compare?'four-language-grid':'lesson-text'}>{(compare?learningLanguages:[displayLang]).map(l=><article key={l} lang={l} dir={l==='ar'?'rtl':'ltr'}><div className="lesson-language"><span>{names[l]}</span><small>{l===(active.sourceLanguage||'en')?t('الأصل','Original','Оригинал','Original'):t('ترجمة الملخص','Translated summary','Перевод обзора','Übersetzter Kurztext')}</small></div>{versions[l]?<><h3>{versions[l]!.title}</h3><p>{versions[l]!.summary}</p></>:<p role="status">{busy?t('نحضّر هذه اللغة…','Preparing this language…','Готовим перевод…','Übersetzung wird vorbereitet…'):t('الترجمة غير متاحة بعد.','Translation not available yet.','Перевод пока недоступен.','Übersetzung noch nicht verfügbar.')}</p>}</article>)}</div><div className="learning-actions"><button className="primary-button" onClick={save} disabled={!ready} aria-pressed={!!selectedSave}><Bookmark size={17}/>{selectedSave?t('محفوظ · إزالة','Saved · remove','Сохранено · удалить','Gespeichert · entfernen'):t('حفظ بكل اللغات','Save all languages','Сохранить все языки','Alle Sprachen speichern')}</button><button className="outline-button" onClick={()=>setReader(true)}><BookOpen size={17}/>{t('المقال الأصلي','Original article','Оригинал статьи','Originalartikel')}</button><a href={active.url} className="lesson-reference" target="_blank" rel="noreferrer">{t('المصدر','Source','Источник','Quelle')}<ArrowUpRight size={15}/></a></div><p className="learning-note">{t('المختارات لها ترجمات معدّة مسبقاً. القصص الجديدة تستخدم ترجمة آلية عبر MyMemory وقد تحتوي أخطاء. الحفظ في هذا المتصفح.','Selected references have prepared translations. New stories use MyMemory machine translation and may contain errors. Saves stay in this browser.','Для избранных статей переводы подготовлены. Новые истории переводит MyMemory; возможны ошибки. Сохранение в этом браузере.','Referenzartikel haben vorbereitete Übersetzungen. Neue Geschichten nutzen MyMemory; Fehler sind möglich. Gespeichert wird in diesem Browser.')}</p></>:<p>{t('اختر قصة محفوظة لتفتحها بلغاتها الأربع.','Choose a saved story to open its four languages.','Выберите сохранённую историю.','Wähle eine gespeicherte Geschichte für ihre vier Sprachversionen.')}</p>}</div></div>
 {savedOnly&&!saved.length&&<p>{t('لا قصص محفوظة بعد.','No saved stories yet.','Пока нет сохранённых историй.','Noch keine gespeicherten Geschichten.')}</p>}{error&&<div className="learning-error" role="alert">{error}<button className="outline-button" disabled={busy} onClick={()=>setAttempt(n=>n+1)}>{t('إعادة المحاولة','Retry','Повторить','Erneut versuchen')}</button></div>}
 <Dialog open={reader} onOpenChange={setReader}><DialogContent className="article-dialog" dir={lang==='ar'?'rtl':'ltr'}><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{t('المقال بلغة المصدر','Article in its source language','Статья на языке источника','Artikel in der Originalsprache')}</DialogDescription></DialogHeader>{selected&&<ArticleReader key={selected.url} story={selected} lang={lang} sourceLang={selected.sourceLanguage||'en'}/>}</DialogContent></Dialog>
 </CollapsibleContent></Collapsible>
}
