import {pick,type Lang} from '@/lib/news-data';
import {ArrowUpRight,Scale} from 'lucide-react';
export default function ReligionGuide({lang}:{lang:Lang}){
 const t=(...v:string[])=>pick(v,lang);
 const references=[
  {url:'https://plato.stanford.edu/entries/philosophy-religion/',type:t('حجج فلسفية','Philosophical arguments','Философские аргументы','Philosophische Argumente'),title:t('هل توجد أسباب للإيمان؟ وأين تقع الاعتراضات؟','Reasons to believe—and arguments against','Основания верить и аргументы против','Gründe zu glauben und Gegenargumente'),source:'Stanford Encyclopedia of Philosophy'},
  {url:'https://plato.stanford.edu/entries/atheism-agnosticism/',type:t('إلحاد ولاأدرية','Atheism & agnosticism','Атеизм и агностицизм','Atheismus & Agnostizismus'),title:t('كيف يختلف الإنكار عن تعليق الحكم؟','Disbelief, uncertainty, and the burden of proof','Неверие, неопределённость и бремя доказательства','Unglaube, Unsicherheit und Beweislast'),source:'Stanford Encyclopedia of Philosophy'},
  {url:'https://www.pewresearch.org/religion/2025/06/09/how-the-global-religious-landscape-changed-from-2010-to-2020/',type:t('بيانات اجتماعية','Social research','Социальные исследования','Sozialforschung'),title:t('كيف تتغير الأديان والمعتقدات في العالم؟','How religious affiliation changes around the world','Как меняется религиозная принадлежность в мире','Wie sich Religionszugehörigkeit weltweit verändert'),source:'Pew Research Center · 2025'},
 ];
 return <div className="religion-guide"><div className="religion-intro"><Scale size={25}/><div><h4>{t('أسئلة كبيرة. مساحة للفحص.','Big questions. Room to examine.','Большие вопросы. Пространство для анализа.','Große Fragen. Raum zum Prüfen.')}</h4><p>{t('حجج مؤيدة ونقدية، تاريخ النصوص، آثار، وأبحاث عن المعتقدات. نميّز بين ما يمكن اختباره وبين الحجج الفلسفية والإيمان؛ شعبية معتقد لا تثبت صحته.','Arguments for and against, textual history, archaeology, and research on belief. Testable claims, philosophical arguments, and faith are different kinds of questions; popularity does not establish truth.','Аргументы за и против, история текстов, археология и исследования верований. Проверяемые утверждения, философские доводы и вера — разные вопросы; популярность не доказывает истинность.','Argumente dafür und dagegen, Textgeschichte, Archäologie und Glaubensforschung. Prüfbare Behauptungen, philosophische Argumente und Glaube sind unterschiedliche Fragen; Beliebtheit beweist keine Wahrheit.')}</p></div></div><div className="religion-references">{references.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer"><small>{r.type}</small><strong>{r.title}<ArrowUpRight size={17}/></strong><span>{r.source} · English</span></a>)}</div><p className="religion-feed-note">{t('مراجع للقراءة باللغة الإنجليزية؛ الأخبار أدناه مجمّعة آلياً ولم تُراجع ادعاءاتها بعد.','English-language reading references; the news below is automatically collected and its claims have not been reviewed.','Справочные материалы на английском; новости ниже собраны автоматически, их утверждения ещё не проверены.','Englischsprachige Referenzen; die folgenden Nachrichten werden automatisch gesammelt, ihre Aussagen sind noch nicht geprüft.')}</p></div>
}
