import {matchesEditionText} from './language-editions';
import {XMLParser} from 'fast-xml-parser';
import {type Lang,type Story} from '@/lib/news-data';
export type FeedContent={html:string;publisherUrl:string;lang:Lang};
const feedContent=new Map<string,FeedContent>();
export const getFeedContent=(url:string)=>feedContent.get(url);
function remember(url:string,value:FeedContent){if(feedContent.size>=2000)feedContent.delete(feedContent.keys().next().value!);feedContent.set(url,value);let total=0;for(const entry of [...feedContent.values()].reverse()){total+=entry.html.length;if(total>3000000)entry.html=''}}
type Feed={name:string;url:string;topic?:string;filter?:boolean;google?:boolean};
const google=(q:string,hl:string,gl:string,ceid:string)=>'https://news.google.com/rss/search?'+new URLSearchParams({q,hl,gl,ceid});
const sources:Record<Lang,Feed[]>={
 ar:[{name:"الدين والأدلة",url:google("(\"فلسفة الدين\" OR \"مقارنة الأديان\" OR \"أدلة وجود الله\" OR \"نقد الدين\" OR \"علم الآثار التوراتي\") when:90d",'ar','LB','LB:ar'),topic:'religion',google:true},{name:'البوابة العربية للأخبار التقنية',url:'https://aitnews.com/feed/',topic:'tech'},{name:'عالم التقنية',url:'https://www.tech-wd.com/wd/feed/',topic:'tech'},{name:'الجزيرة',url:'https://www.aljazeera.net/aljazeerarss/all',filter:true},{name:'اكتشافات · Google News',url:google('علوم OR اكتشاف OR "ذكاء اصطناعي" OR روبوت OR اختراع OR فضاء OR "أبحاث طبية" OR آثار OR محيطات when:14d','ar','LB','LB:ar'),google:true},{name:'علوم وفضاء · Google News',url:google('(فضاء OR فلك OR كوكب OR محيطات OR حفريات OR روبوت OR اختراع) when:14d -حرب -سياسة','ar','LB','LB:ar'),google:true},{name:'طب واكتشافات · Google News',url:google('("دراسة علمية" OR "علاج جديد" OR "طاقة متجددة" OR "اكتشاف أثري") when:14d','ar','LB','LB:ar'),google:true},{name:'لبنان · Google News',url:google('لبنان (تكنولوجيا OR ابتكار OR علوم OR اكتشاف OR ثقافة OR بيئة OR طب) when:30d','ar','LB','LB:ar'),topic:'lebanon',google:true}],
 en:[{name:"Religion & evidence",url:google("(\"philosophy of religion\" OR \"evidence for God\" OR \"religious archaeology\" OR \"religious skepticism\" OR \"historical Jesus\") when:90d",'en','US','US:en'),topic:'religion',google:true},{name:'ScienceDaily',url:'https://www.sciencedaily.com/rss/all.xml'},{name:'NASA',url:'https://www.nasa.gov/feed/',topic:'space'},{name:'MIT News · AI',url:'https://news.mit.edu/rss/topic/artificial-intelligence2',topic:'ai'},{name:'BBC · Science',url:'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml'},{name:'BBC · Technology',url:'https://feeds.bbci.co.uk/news/technology/rss.xml',topic:'tech'}],
 ru:[{name:"Религия и исследования",url:google("(\"философия религии\" OR \"доказательства бытия Бога\" OR \"критика религии\" OR \"библейская археология\") when:90d",'ru','DE','DE:ru'),topic:'religion',google:true},{name:'Naked Science',url:'https://naked-science.ru/feed'},{name:'N + 1',url:'https://nplus1.ru/rss'},{name:'Наука · Google News',url:google('наука OR робот OR космос OR медицина OR изобретение OR археология OR кибербезопасность when:14d','ru','DE','DE:ru'),google:true}],
 de:[{name:"Religion & Forschung",url:google("(\"Religionsphilosophie\" OR \"Gottesbeweise\" OR \"Religionskritik\" OR \"biblische Archäologie\") when:90d",'de','DE','DE:de'),topic:'religion',google:true},{name:'scinexx',url:'https://www.scinexx.de/feed/'},{name:'heise online',url:'https://www.heise.de/rss/heise-atom.xml',topic:'tech'},{name:'Wissenschaft · Google News',url:google('Forschung OR Weltraum OR Erfindung OR Archäologie OR Ozean OR Medizin when:14d','de','DE','DE:de'),google:true},{name:'Ukraine §24 · Google News',url:google('Ukraine ("§24" OR "§ 24" OR "Paragraph 24" OR Aufenthaltserlaubnis OR vorübergehender Schutz) Deutschland when:90d','de','DE','DE:de'),topic:'ukraine',google:true}]
};
const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',processEntities:true,htmlEntities:true,ignoreDeclaration:true});
const cache=new Map<string,{time:number;data:unknown}>();
function val(v:any):string{if(v==null)return '';if(typeof v==='string'||typeof v==='number')return String(v);if(Array.isArray(v))return val(v[0]);return val(v['#text']||v.__cdata||'')}
function clean(v:any){return val(v).replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(Number(n),1114111))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(Math.min(parseInt(n,16),1114111))).replace(/\s+/g,' ').trim()}
function safe(v:string){try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function classify(s:string,fallback='tech'){const rules:[string,RegExp][]=[['religion',/religion|theolog|atheis|agnostic|biblical|gottesbeweis|религи|атеизм|فلسفة الدين|نقد الدين|مقارنة الأديان|وجود الله/i],['security',/cyber|privacy|malware|ransomware|sicherheit|datenschutz|кибер|приватност|خصوصية|سيبراني|اختراق/i],['ai',/\bAI\b|artificial intelligence|\bKI\b|intelligenz|нейросет|искусственн|ذكاء اصطناعي|الذكاء الاصطناعي|تعلم آلي/i],['robots',/robot|робот|روبوت/i],['space',/alien|\bUAP\b|\bUFO\b|exoplanet|space|nasa|astronom|weltraum|космос|космич|инопланет|الفضاء|فضائي|فلكي|كوكب|ثقب أسود|نيوترينو|مجرة/i],['health',/medical|cancer|clinical|gene therap|medicine|medizin|krebs|терап|медицин|лечени|рак |علاج|سرطان|طبية|الطب|دواء|أدوية/i],['energy',/energy|fusion|battery|energie|batterie|энерги|батаре|طاقة|بطارية/i],['earth',/ocean|archaeolog|archäolog|океан|археолог|محيط|آثار|أثري/i],['weird',/ig nobel|unusual|weird|kurios|необыч|غريب|طريف/i]];return rules.find(([,re])=>re.test(s))?.[0]||fallback}
async function getFeed(f:Feed,lang:Lang):Promise<{articles:Story[];status:{name:string;ok:boolean;count:number}}>{try{const response=await fetch(f.url,{cache:'no-store',signal:AbortSignal.timeout(11000),headers:{'User-Agent':'NABD/1.0 (RSS news reader)','Accept':'application/rss+xml,application/atom+xml,application/xml,text/xml'}});if(!response.ok)throw Error('feed unavailable');const xml=await response.text();if(xml.length>3500000)throw Error('feed too large');const data=parser.parse(xml);let items=data.rss?.channel?.item||data.feed?.entry||[];if(!Array.isArray(items))items=[items];const articles:Story[]=items.map((item:any)=>{const links=Array.isArray(item.link)?item.link:[item.link];const link=links.find((x:any)=>x?.['@_rel']==='alternate')||links[0];const url=safe(typeof link==='string'?link:link?.['@_href']||val(link));const title=clean(item.title);const summary=f.google?'':clean(item.description||item.summary).slice(0,230);const rawDate=val(item.pubDate||item.published||item.updated||item['dc:date']);const d=new Date(rawDate);const category=f.topic==='lebanon'||f.topic==='ukraine'||f.topic==='religion'?f.topic:classify(title,f.topic||classify(summary,'tech'));const media=item['media:content']||item['media:thumbnail']||item.enclosure;const med=Array.isArray(media)?media[0]:media;const content=val(item['content:encoded']||item.description||item.content||item.summary);remember(url,{html:val(item['content:encoded']||item.content||'').slice(0,120000),publisherUrl:safe(item.source?.['@_url']||''),lang});const embedded=content.match(/<img[^>]+src=["']([^"']+)["']/i)?.[1];const img=safe(med?.['@_url']||embedded||'');return {id:url,title,summary,sourceLanguage:lang,category,source:clean(item.source)||f.name,url,date:Number.isNaN(d.getTime())?'':d.toISOString(),image:img&&(/image/.test(med?.['@_type']||'')||/\.(jpg|png|webp|jpeg)(\?|$)/i.test(img))?img:undefined,evidence:'unreviewed' as const};}).filter((s:Story)=>s.url&&s.title&&(!s.date||Date.parse(s.date)<Date.now()+86400000)&&(f.topic!=='religion'||(!/الدين العام|صندوق النقد|ديون|موازنة|ائتماني/.test(s.title)&&/religio|theolog|atheis|agnostic|God|Jesus|biblic|faith|belief|archaeolog|Gott|Bibel|Glaub|Archäolog|религ|Бог|атеис|библе|веры|археолог|الدين|الأديان|دينيا|ديني|إلحاد|الإلحاد|الله|الآثار|التوراة|القرآن|الإنجيل/i.test(s.title)))&&(!f.filter||classify(s.title+' '+s.summary,'none')!=='none'&&!/مبابي|مباراة|كرة القدم|الدوري|حرب|معارك/.test(s.title)));return {articles,status:{name:f.name,ok:articles.length>0,count:articles.length}}}catch{return {articles:[],status:{name:f.name,ok:false,count:0}}}}
export async function getEdition(lang:Lang,refresh=false){const cached=cache.get(lang);if(!refresh&&cached&&Date.now()-cached.time<600000)return cached.data as FeedResponse;const all=await Promise.all(sources[lang].map(f=>getFeed(f,lang)));const seen=new Set<string>();const articles=all.flatMap(x=>x.articles).filter(s=>{if(!matchesEditionText(s.title,lang))return false;if(/أبراج|نهاية العالم|الفضاء العام|فضاء السيادة|توقعات الطقس|مبابي|فينيسيوس|الشعب الصحراوي|horoscope|astrologie|гороскоп/i.test(s.title))return false;if(seen.has(s.url))return false;seen.add(s.url);return true}).sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0));const data={articles,sources:all.map(x=>x.status),fetchedAt:new Date().toISOString()};if(articles.length)cache.set(lang,{time:Date.now(),data});return data}
export type FeedResponse={articles:Story[];sources:{name:string;ok:boolean;count:number}[];fetchedAt:string};
