export type Lang='ar'|'en'|'ru'|'de';
export const pick=(v:string[],l:Lang)=>v[['ar','en','ru','de'].indexOf(l)]||v[1];
export type Story={id:string;title:string;summary:string;category:string;source:string;url:string;date:string;image?:string;evidence:'official'|'research'|'unreviewed';kind?:string;credit?:string;creditUrl?:string;translated?:boolean;sourceLanguage?:Lang;};
export const topics=[['all','الكل','All stories','Все новости','Alle Nachrichten'],['ai','ذكاء اصطناعي','AI','ИИ','KI'],['tech','تقنية وابتكارات','Technology','Технологии','Technologie'],['space','فضاء وحياة أخرى','Space & aliens','Космос и жизнь','Weltraum & Leben'],['health','إنجازات طبية','Medical advances','Медицина','Medizin'],['weird','غريب وممتع','Weird & wonderful','Необычное','Kurioses'],['robots','روبوتات','Robotics','Роботы','Robotik'],['energy','طاقة المستقبل','Future energy','Энергия','Zukunftsenergie'],['security','أمن وخصوصية','Security & privacy','Безопасность','Sicherheit'],['earth','آثار ومحيطات','Earth & archaeology','Земля и археология','Erde & Archäologie'],['religion','الدين والتاريخ والأدلة','Religion & evidence','Религия и доказательства','Religion & Evidenz'],['lebanon','من لبنان','Lebanon','Ливан','Libanon'],['ukraine','أوكرانيون في ألمانيا · §24','Ukraine in Germany · §24','Украинцы в Германии · §24','Ukraine in Deutschland · §24']];
export const topicName=(id:string,l:Lang)=>{const t=topics.find(t=>t[0]===id);return t?pick(t.slice(1),l):id};
export const spaceImage='https://cdn.esawebb.org/archives/images/screen/weic2205a.jpg';
export const robotImage='https://upload.wikimedia.org/wikipedia/commons/f/f8/Sophia_%28robot%29.jpg';
export const beirutImage='https://upload.wikimedia.org/wikipedia/commons/9/9e/Beirut_Skyline_-_panoramio.jpg';
export function curated(l:Lang,includeTranslations=false):Story[]{const stories:Story[]=[
{id:'webb-life',category:'space',title:pick(['هل نحن وحدنا؟ ما الذي يخبرنا به جيمس ويب حقاً؟','Are we alone? What Webb can actually tell us','Одиноки ли мы? Что может рассказать «Уэбб»','Sind wir allein? Was Webb wirklich verraten kann'],l),summary:pick(['رصد جزيء محتمل لا يعني اكتشاف حياة. تشرح ناسا لماذا نحتاج إلى أدلة متعددة وفهم بيئة الكوكب قبل إعلان كهذا.','A possible molecule is not a discovery of life. NASA explains why atmospheric signals need multiple lines of evidence and planetary context.','Возможное обнаружение молекулы не означает открытие жизни. NASA объясняет, зачем нужны несколько признаков и контекст планеты.','Ein mögliches Molekül ist kein Nachweis von Leben. NASA erklärt, warum mehrere Belege und Wissen über den Planeten nötig sind.'],l),source:'NASA',url:'https://science.nasa.gov/blogs/webb/2025/04/18/how-nasas-webb-telescope-supports-our-search-for-life-beyond-earth/',date:'2025-04-18',image:spaceImage,evidence:'research',kind:'explainer',credit:'Cosmic Cliffs · NASA, ESA, CSA, STScI · 2022 · CC BY 4.0 · cropped',creditUrl:'https://esawebb.org/images/weic2205a/',translated:l!=='en'},
{id:'alphagenome',category:'ai',title:pick(['أطلس جديد يتنبأ بأثر 9 مليارات تغيّر في الحمض النووي','An AI atlas maps 9 billion possible DNA changes','ИИ-атлас прогнозирует 9 миллиардов изменений ДНК','KI-Atlas prognostiziert 9 Milliarden DNA-Veränderungen'],l),summary:pick(['نشرت DeepMind أطلس AlphaGenome لتوقع التأثيرات الجزيئية لتغيرات الحمض النووي. أداة للبحث، وليست علاجاً أو تشخيصاً مثبتاً.','DeepMind released AlphaGenome Atlas to predict molecular effects of DNA variants. A research tool, not a proven treatment or diagnostic.','DeepMind представила AlphaGenome Atlas для прогноза эффектов вариантов ДНК. Это исследовательский инструмент, не лечение или диагноз.','DeepMind stellt AlphaGenome Atlas für Vorhersagen molekularer Auswirkungen von DNA-Varianten vor. Ein Forschungswerkzeug, keine geprüfte Therapie oder Diagnose.'],l),source:'Google DeepMind',url:'https://deepmind.google/blog/alphagenome-atlas-a-predictive-map-of-every-possible-dna-letter-change-in-the-human-genome/',date:'2026-09-08',evidence:'research',kind:'genome',translated:l!=='en'},
{id:'casgevy',category:'health',title:pick(['كريسبر يدخل العلاج: ما الذي اعتمدته FDA؟','CRISPR reaches the clinic: what did the FDA approve?','CRISPR в клинике: что одобрила FDA?','CRISPR in der Klinik: Was hat die FDA zugelassen?'],l),summary:pick(['تدرج FDA علاج Casgevy لحالات محددة من فقر الدم المنجلي والثلاسيميا المعتمدة على نقل الدم لدى مرضى بعمر 12 عاماً فأكثر. المصدر الرسمي يوضح الأهلية والمخاطر.','The FDA lists Casgevy for specified sickle cell disease and transfusion-dependent beta-thalassemia indications in patients aged 12 and older. Eligibility and risks are in the official label.','FDA указывает Casgevy для определённых форм серповидноклеточной болезни и бета-талассемии у пациентов от 12 лет. Условия и риски — в инструкции.','Die FDA führt Casgevy für bestimmte Formen von Sichelzellkrankheit und transfusionsabhängiger Beta-Thalassämie ab 12 Jahren. Voraussetzungen und Risiken stehen in der Fachinformation.'],l),source:'FDA',url:'https://www.fda.gov/vaccines-blood-biologics/casgevy',date:'2023-12-08',evidence:'official',kind:'medical',translated:l!=='en'},
{id:'ig-nobel',category:'weird',title:pick(['علم يجعلك تضحك… ثم تفكّر: اكتشف إيغ نوبل','Science that makes you laugh, then think: the Ig Nobels','Наука, которая смешит и заставляет думать: Ig Nobel','Forschung zum Lachen und Nachdenken: die Ig Nobels'],l),summary:pick(['أبحاث غير متوقعة وأسئلة جادة في سجل جوائز إيغ نوبل، مع روابط للباحثين والمراجع الأصلية.','Explore unexpected research in the Ig Nobel winners archive, with researchers and original references.','Необычные исследования в архиве лауреатов Ig Nobel со ссылками на авторов и работы.','Ungewöhnliche Forschung im Archiv der Ig-Nobelpreisträger, mit Forschenden und Originalreferenzen.'],l),source:'Improbable Research',url:'https://improbable.com/ig/winners/',date:'',evidence:'official',kind:'explainer',translated:l!=='en'},
...(l==='de'?[{id:'section24',category:'ukraine',title:'§24: Aufenthaltsrecht, Arbeit und aktuelle Änderungen',summary:'Offizielle Seiten haben unterschiedliche Aktualisierungsstände. Die deutsche Aufenthaltsseite beschreibt eine weitere Fortgeltung für ukrainische Staatsangehörige mit am 1. Februar 2027 gültigem Titel bis 4. März 2028. Für Drittstaatsangehörige gelten Ausnahmen. Zusammenfassung geprüft am 26. September 2026; maßgeblich ist die aktuelle amtliche Regelung.',source:'Germany4Ukraine',url:'https://www.germany4ukraine.de/DE/einreise-aufenthalt-und-rueckkehr/ukraine-aufenthaltserlaubnis/seite_node.html',date:'2026-09-26',evidence:'official' as const,kind:'guide'}]:[])
];return stories.filter(s=>includeTranslations||!s.translated).map(s=>({...s,sourceLanguage:s.id==='section24'?'de':'en'}));}
